#pragma once

#define FPS 30

#define HOVER_TONE al_map_rgba(255,255,255,200)
#define PRESSED_TONE al_map_rgba(100,100,100,200)
#define HOVER_TONE al_map_rgba(255,255,255,200)

// Screen size
#define SCREEN_RATIO (16.0/9.0)
#define SCREEN_WIDTH 800.0
#define SCREEN_HEIGHT (SCREEN_WIDTH / SCREEN_RATIO)

// Margins for board
#define LEFT_BOARD_MARGIN  SCREEN_WIDTH * 0.03
#define RIGHT_BOARD_MARGIN SCREEN_WIDTH * 0.03
#define UPPER_BOARD_MARGIN SCREEN_HEIGHT * 0.03
#define LOWER_BOARD_MARGIN SCREEN_HEIGHT * 0.3

// Board dimensions
#define BOARD_HEIGHT SCREEN_HEIGHT - UPPER_BOARD_MARGIN - LOWER_BOARD_MARGIN
#define BOARD_WIDTH  SCREEN_WIDTH - LEFT_BOARD_MARGIN - RIGHT_BOARD_MARGIN
#define BOARD_XPOS LEFT_BOARD_MARGIN 
#define BOARD_YPOS UPPER_BOARD_MARGIN
// Floor dimensions
#define FLOOR_SEPARATION SCREEN_WIDTH * 0.01
#define FLOOR_WIDTH (BOARD_WIDTH - 2 * FLOOR_SEPARATION) / 3
#define FLOOR_HEIGHT BOARD_HEIGHT

//Floor positions
#define FLOOR_YPOS BOARD_YPOS

#define FLOOR1_XPOS BOARD_XPOS
#define FLOOR2_XPOS BOARD_XPOS + FLOOR_WIDTH + FLOOR_SEPARATION
#define FLOOR3_XPOS BOARD_XPOS + 2 * (FLOOR_WIDTH + FLOOR_SEPARATION)

// Tile dimensions
#define TILE_SEPARATION 
